### ISSUE TITLE
Hello Li , about the code release and dataset 

### ISSUE THREAD

**Issue by DuTim** [Chain123/CAT-ART#1]
Hi I read your article on arxiv, your work is very advanced work in CDR, I would like to know more about this work, when can I see the code?    Is it possible to provide the dataset😄  ? 

Thanks !

**Comment by Chain123** [comment]
Hi there,

I original plan to open-source the code after the conference (WSDM-23).
However, I can release it in advance, give me a few days to tidy up my
code. As for the datasets, because Tencent collects them, I need to
communicate with the company first. Hopefully, it will be available through
email request.

Best
Chenglin

**Comment by DuTim** [comment]
Thank you very much for your reply , and I look forward to your future work.
Thanks !!!
