### ISSUE TITLE
Hello Li, about the amazaon dataset

### ISSUE THREAD

**Issue by 630996818** [Chain123/CAT-ART#3]
Hello Li, I read your article recently, and I want to run the code, but failed. If the dataset in your paper can't be released, could you please give me the amazon dataset that has been processed?

And the implementation of class Quantize in .vq is not included in the open source code, is it unnecessary?

Best wishes!

**Comment by Chain123** [comment]
Hello,

Due to certain policies in China, I can not directly release the original
data collected at Tencent, you may need to email them (e.g., Kong who is
responsible for this at Tencent, ***@***.***) to see if it's
possible to get their industrial dataset. Furthermore, we did not use the
amazon dataset cause there are too few overlapped users between
multiple domains (>=3 domains), but you can try it yourself. Moreover, the
.vq stuff is not relevant to this project and is misplaced here. I will
remove it from the code when I have time.

Best regards
Chenglin

**Comment by Chain123** [comment]
echokong AT tencent dot com

**Comment by HuanghuaGo** [comment]
dear author, is there any chance that you can kindly release the implementation of class Quantize in .vq? Many thanks.

from .vq import Quantize

**Comment by Chain123** [comment]
Hi there, the Quantize is not related to this project. However, if you are
interested you can refer to the implementation of VQ-VAE at
https://paperswithcode.com/paper/neural-discrete-representation-learning#code
(choose the one you like)

Best regards
Chenglin
